### ISSUE TITLE
pip install -r requirements.txt fails with errors

### ISSUE THREAD

**Issue by scottw-finao** [hologram-io/spacebridge#1]
~/src/spacebridge $ sudo pip install -r requirements.txt 
[sudo] password for swood: 
Downloading/unpacking easygui==0.97.4 (from -r requirements.txt (line 1))
  Downloading easygui-0.97.4-py2.py3-none-any.whl (78kB): 78kB downloaded
Downloading/unpacking paramiko==2.3.1 (from -r requirements.txt (line 2))
  Downloading paramiko-2.3.1-py2.py3-none-any.whl (182kB): 182kB downloaded
Downloading/unpacking PyInstaller==3.3 (from -r requirements.txt (line 3))
  Downloading PyInstaller-3.3.tar.gz (3.5MB): 3.5MB downloaded
  Running setup.py (path:/tmp/pip-build-C46OWp/PyInstaller/setup.py) egg_info fo
r package PyInstaller
    
    no previously-included directories found matching 'bootloader/build'
    no previously-included directories found matching 'bootloader/.waf-*'
    no previously-included directories found matching 'bootloader/.waf3-*'
    no previously-included directories found matching 'bootloader/waf-*'
    no previously-included directories found matching 'bootloader/waf3-*'
    no previously-included directories found matching 'bootloader/_sdks'
    no previously-included directories found matching 'bootloader/.vagrant'
    warning: no previously-included files found matching 'bootloader/.lock-waf*'
    no previously-included directories found matching 'doc/source'
    no previously-included directories found matching 'doc/_build'
    warning: no previously-included files matching '*.tmp' found under directory
 'doc'
    no previously-included directories found matching 'old'
    no previously-included directories found matching 'scripts'
    no previously-included directories found matching 'tests/scripts'
    no previously-included directories found matching '.github'
    warning: no previously-included files found matching '.*'
    warning: no previously-included files found matching '*.yml'
    warning: no previously-included files found matching '*~'
    warning: no previously-included files found matching '.directory'
Downloading/unpacking requests==2.18.4 (from -r requirements.txt (line 4))
  Downloading requests-2.18.4-py2.py3-none-any.whl (88kB): 88kB downloaded
Requirement already satisfied (use --upgrade to upgrade): pyasn1>=0.1.7 in /usr/
lib/python2.7/dist-packages (from paramiko==2.3.1->-r requirements.txt (line 2))
Downloading/unpacking bcrypt>=3.1.3 (from paramiko==2.3.1->-r requirements.txt (
line 2))
  Downloading bcrypt-3.1.4.tar.gz (42kB): 42kB downloaded
  Running setup.py (path:/tmp/pip-build-C46OWp/bcrypt/setup.py) egg_info for pac
kage bcrypt
    
    warning: no previously-included files found matching 'requirements.txt'
    warning: no previously-included files found matching 'tasks.py'
    warning: no previously-included files found matching '.travis.yml'
    warning: no previously-included files found matching 'wheel-scripts'
    warning: no previously-included files found matching 'Jenkinsfile'
    warning: no previously-included files found matching '.jenkins'
    warning: no previously-included files matching '*' found under directory '.j
enkins'
    warning: no previously-included files matching '*' found under directory 'wh
eel-scripts'
    no previously-included directories found matching '.travis'
Downloading/unpacking pynacl>=1.0.1 (from paramiko==2.3.1->-r requirements.txt (
line 2))
  Downloading PyNaCl-1.2.1.tar.gz (3.3MB): 3.3MB downloaded
  Running setup.py (path:/tmp/pip-build-C46OWp/pynacl/setup.py) egg_info for packag
e pynacl                                                                           
    Download error on https://pypi.python.org/simple/cffi/: [Errno -2] Name or serv
ice not known -- Some packages may not be found!                                   
    Couldn't find index page for 'cffi' (maybe misspelled?)
    Download error on https://pypi.python.org/simple/: [Errno -2] Name or service n
ot known -- Some packages may not be found!                                        
    No local packages or download links found for cffi>=1.4.1
    Traceback (most recent call last):                                             
      File "<string>", line 17, in <module>
      File "/tmp/pip-build-C46OWp/pynacl/setup.py", line 251, in <module>
        "Programming Language :: Python :: 3.6",
      File "/usr/lib/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 262, in __in
it__                                                                               
        self.fetch_build_eggs(attrs['setup_requires'])
      File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 287, in fetc
h_build_eggs
        replace_conflicting=True,
      File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 631, in resolv
e
        dist = best[req.key] = env.best_match(req, ws, installer)
      File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 874, in best_m
atch
        return self.obtain(req, installer)
      File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 886, in obtain
        return installer(requirement)
      File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 338, in fetc
h_build_egg
        return cmd.easy_install(req)
      File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", l
ine 630, in easy_install
        raise DistutilsError(msg)
    distutils.errors.DistutilsError: Could not find suitable distribution for Requi
rement.parse('cffi>=1.4.1')
    Complete output from command python setup.py egg_info:
    Download error on https://pypi.python.org/simple/cffi/: [Errno -2] Name or serv
ice not known -- Some packages may not be found!

Couldn't find index page for 'cffi' (maybe misspelled?)

Download error on https://pypi.python.org/simple/: [Errno -2] Name or service not k
nown -- Some packages may not be found!

No local packages or download links found for cffi>=1.4.1

Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip-build-C46OWp/pynacl/setup.py", line 251, in <module>

    "Programming Language :: Python :: 3.6",

  File "/usr/lib/python2.7/distutils/core.py", line 111, in setup
    _setup_distribution = dist = klass(attrs)

  File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 262, in __init__

    self.fetch_build_eggs(attrs['setup_requires'])

  File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 287, in fetch_bu
ild_eggs

    replace_conflicting=True,

  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 631, in resolve

    dist = best[req.key] = env.best_match(req, ws, installer)

  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 874, in best_match

    return self.obtain(req, installer)

  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 886, in obtain
    return installer(requirement)

  File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 338, in fetch_bu
ild_egg

    return cmd.easy_install(req)

  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 
630, in easy_install

    raise DistutilsError(msg)

distutils.errors.DistutilsError: Could not find suitable distribution for Requireme
nt.parse('cffi>=1.4.1')

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip-build-C46OWp/
pynacl
Storing debug log for failure in /root/.pip/pip.log

**Comment by DomAmato** [comment]
closing this since we are no longer supporting python 2 for our projects
